### ISSUE TITLE
Cannot change MAC address on Macbook Pro 2018 and newer

### ISSUE THREAD

**Issue by blaesus** [feross/SpoofMAC#87]
## Solution: Update to macOS 10.15 Catalina

Updating to macOS 10.15 Catalina appears to fix the issue.

## Original report

I cannot randomize any MAC address with `spoof-mac`. The program returns fine, but the MAC addresses are not changed. I tried changing `en0` and `en1` and neither took effect. The Node.js `spoof` doesn't work either.

I tried rebooting or signing in as another user; neither worked.

By the way, `sudo ifconfig en0 ether aa:bb:cc:dd:ee:ff` doesn't work either.

spoof-mac version: **2.1.1**

<img width="1541" alt="untitled" src="https://user-images.githubusercontent.com/233354/42925131-a552ef0c-8b5f-11e8-91e9-6aa517d15e33.png">
<img width="698" alt="untitled 2" src="https://user-images.githubusercontent.com/233354/42925146-bc9cdb32-8b5f-11e8-9df1-e0be3c1afcce.png">

This is a new machine. I have another Macbook which runs on 10.12, where `spoof-mac` works just fine.

Thanks for making the tool! It is really helpful.

**Comment by eric8810** [comment]
Same problem，i tried many tools like python version, wifi-spoof etc. 
Even the cmdline "if en0 ether xx:xx:xx" has been confirmed failed.
Seems like the new machine blocks up the spoof interface.

2018 new mbp 15

**Comment by jonluca** [comment]
Confirming the same issue.

Edit: Problem discussed previously was  **unrelated**

**Comment by TkTech** [comment]
@jonluca your problem probably isn't the same. Can you try turning off System Integrity Protection temporarily and try again?

**Comment by jonluca** [comment]
Issue seems to just be with new 2018 MBPs

~~SIP is turned off.~~

~~I believe it is the same problem. I’m running ‘sudo ifconfig en0 ether xx:xx:xx:xx:xx:xx’ and it A) fails silently and B) returns a 0 exit code.~~

~~The console just shows what system events are happening right after. Does your console not show those events?~~

**Comment by TkTech** [comment]
No, the error message you're getting is because the code signature database (DetachedSignatures) can't be opened. Either it's really gone, or SIP is blocking it from being opened (which happens). Either way that message usually means your permssions are messed up somewhere.

You also can't change the MAC, but that's the same for everyone at the moment. Two different problems.

**Comment by jonluca** [comment]
Ah gotcha.

The DetachedSignatures file actually doesn’t exist - is that an issue?

I’m running 10.14 beta by the way.

**Comment by TkTech** [comment]
Really hard for me to debug, I know users are having lots of trouble with OSX but with only one machine available to me with the real NIC I'm stuck on an older version of OS X. Pretty much turns into a game of 20 questions.

If you download an unsigned app, you know the prompt to confirm/deny running it? If you hit accept, close the app, and run it again, does the prompt reappear or does it remember it? If it remembers it, that means 10.14 has moved the signatures from DetachedSignatures to somewhere new. If it keeps asking you, then OS X can't create the database file and that usually means either the permissions are messed up, or something moved the /private/var -> /var symlink

One important question; is this a fresh install of the beta, or installed over an older version?

**Comment by jonluca** [comment]
Removed so as to not clog up conversation. This problem is unrelated to lack of ability to spoof mac address.

**Comment by TkTech** [comment]
Well, try to get rid of one problem. If you turn off the OS X firewall under preferences and restart you should get rid of the `socketfilterfw` errors. Try that and see what you get.

**Comment by jonluca** [comment]
Removed so as to not clog up conversation. This problem is unrelated to lack of ability to spoof mac address.

**Comment by TkTech** [comment]
-67062 from taskgated is "code object is not signed at all", so it's still a code signing issue. 

My guess at the moment:

It doesn't look like it's intentional, since in that case they would have just `return 0;` in the framework, or only allowed an internal signature to make the change. Instead, *something somewhere*, probably part of the networking daemon, doesn't seem to be signed properly in the beta, and OS X won't allow the change from an unsigned app.

**Comment by eric8810** [comment]
MacOS error: -67062
same return
I tried with internal term console, still the same

**Comment by jonluca** [comment]
Now I feel quite dumb.

I use `zsh`, and my terminal prompt has a cwd git status indicator. Git is installed through brew, and as such is not signed. After every command, zsh runs `git status` in the current directory, and that's what the error is. 

If I run in it raw bash with no prompt, `taskgated` disappears.

**Comment by feross** [comment]
Confirmed that this has stopped working on 2018 MBPs. The web has no answers either.

If anyone has information about how to fix this, please share.

**Comment by ben-richardson** [comment]
Having the same issue on a MacBook Pro 13-inch (2018).

Is there any further sense of whether this is Apple-intentional, a hardware issue, or a bug?

**Comment by phaberest** [comment]
I'm on the same boat...did any of you find a solution or workaround to this issue?

**Comment by Cfretz244** [comment]
I can also confirm this isn't working on the 2018 MacBooks. Unfortunate. It's not like I'm spoofing my MAC all the time, but it can be very situationally useful.

**Comment by TkTech** [comment]
Can anyone with one of the new macbooks try changing their address to anything with the OUI 88:E9:FE? Ex, 88:E9:FE:AA:AA:AA.

**Comment by ben-richardson** [comment]
@TkTech Doesn't work. MAC is not changed. Tested on MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports).

**Comment by TkTech** [comment]
@ben-richardson thank you for trying it out, it's very hard to test hardware problems without access to the hardware!

Were the first 3 octets of the interface you tried to change 88:E9:FE originally?

**Comment by ben-richardson** [comment]
@TkTech Nope. Originally F0:XX:XX…

**Comment by TkTech** [comment]
@ben-richardson F0:76:6F, F0:24:75, F0:79:60, F0:18:98? (You guys don't need to censor the first 3 octets, they just tell you the manufacturer and are not sensitive, called an [OUI](https://en.wikipedia.org/wiki/Organizationally_unique_identifier))

**Comment by ben-richardson** [comment]
@TkTech Ha, OK. F0:18:98

**Comment by TkTech** [comment]
@ben-richardson perfect, can you try changing the address to F0:18:98:AA:AA:AA?

**Comment by ben-richardson** [comment]
@TkTech Tried, no change. Does not change MAC.

**Comment by blaesus** [comment]
Same here. My OUI starts with `88:E9:FE`. I tried to change only the last byte of MAC and it doesn't work: the same way it failed before, returning without error but the MAC is not changed.

**Comment by jonluca** [comment]
Could someone on Mojave but with a pre 2018 MBP upload their `ifconfig` binary? 

I doubt there’ll be a difference but it’s best to double check.

**Comment by yspreen** [comment]
Additional info: I tried changing my (2018) mac address in the last byte only, still does not work. This is not about manufacturer protection.

**Comment by halo** [comment]
I [found](https://forums.developer.apple.com/thread/106768) a suggestion to determine whether this is a software or a hardware issue:

> You could find out by booting from USB other OS, which has MBP2018 LAN card driver.
I would be really suprised to see if hardware chip would not allow to send packet with MAC address other than factory assigned

Could anybody with a 2018 MBP try that? I.e. boot with [Tails](https://tails.boum.org/contribute/design/installation/) or [Ubuntu](https://tutorials.ubuntu.com/tutorial/try-ubuntu-before-you-install#0) or even Windows via Bootcamp and try to change the MAC address there.

**Comment by treku** [comment]
It is not looking good on brand new MBP 2018. Changing mac address on factory default High Sierra was working with no problems (not sure about SpoolMAC thou, but it might work as well). Now when upgraded to Mojave, both options (via iptables command line) and SpoolMAC doesn't work. I think Apple blocked this tool which is not very good if you are changing the address in hotels or airports to get free wifi for longer periods. Cheked logs when trying to change it, nothing there.

**Comment by blaesus** [comment]
Update: When I plugged in an iPad as a networking device (en9), spoofing does work. Unfortunately, spoofing built-in devices doesn't work. (I use Mojave now.)

**Comment by yspreen** [comment]
> Changing mac address on factory default High Sierra was working with no problems

How? I'm on HS and nothing works for me.

**Comment by TkTech** [comment]
@y-spreen with what model hardware? This is looking like a driver/hardware issue with the built-in wifi in recent MacBooks with High Sierra only.

**Comment by treku** [comment]
@y-spreen I tried on High Sierra with just a command line similar to this: 
`sudo ifconfig en0 ether xx:xx:xx:xx:xx:xx`
This is no longer working since I updated to Mojave.

**Comment by yspreen** [comment]
@TkTech MBP 2018

**Comment by Konstigt** [comment]
Have this issue, MacBook Pro (15-inch, 2016) + Mojave

**Comment by joachimtingvold** [comment]
> Update: When I plugged in an iPad as a networking device (en9), spoofing does work. Unfortunately, spoofing built-in devices doesn't work. (I use Mojave now.)

@blaesus, I'm trying with an USB-C Ethernet adapter (Belkin F2CU040), and I'm not able to change the MAC address at all on that one either, so it's not only limited to built-in devices. Running Mojave on 2018 MBP.

**Comment by joachimtingvold** [comment]
Also, I'd suggest everyone reading this thread/issue to submit a feedback to Apple (regardless if it's a bug or "by design"). Since Apple tends to adhere to privacy concerns, letting their users be able to randomize the WiFi MAC address should be of interest to them.

https://www.apple.com/feedback/macbookpro.html

**Comment by lucafrost** [comment]
Reporting the same issue on a 2017 MBP running Mojave... Kept the OUI octets the same, SIP is still enabled, however, I strongly suspect this is not the issue.

<img width="602" alt="screenshot 2018-11-26 12 30 37" src="https://user-images.githubusercontent.com/38602171/49001968-a2d3ec80-f177-11e8-8685-bf4f3845b6af.png">

I'll submit this as feedback to Apple, might also speak to a friend at the Genius Bar - not sure how much help they'll be lol.

**Comment by lucafrost** [comment]
Here's a boilerplate Bug Report message for those who wish to submit a request:

```
To whom it may concern,

I'm running [macOS Version] on a [Hardware Model].

As someone concerned with Privacy, I'm very worried with an issue resulting in me being unable to change the Mac address of my network card via Terminal. Use of the command 'ifconfig en0 | grep ether 00:00:00:.....' executes without error, however, option-clicking on WiFi in the Menu bar yields no change to the MAC address. 

The WiFi is enabled, but disconnected from all networks. I've kept the first 3 octets of the desired Mac address the same as the OUI in case that was the cause of the issue to no avail. And SIP is enabled.

Please provide a means to remedy the issue for your privacy-conscious users.

Regards,

```
Link: [https://www.apple.com/feedback/macbookpro.html](https://www.apple.com/feedback/macbookpro.html)

**Comment by danipolo** [comment]
Any solution by now? That's so sad. Spending good money on a laptop and having this kind of issues. So bad.

**Comment by jonluca** [comment]
Unfortunately no.

Today I doubled down to see if it was a hardware issue (or at least lower level than macOS kernel). I've attempted to get the new MacbookPro15,1 to boot from Linux, but that also has issues. Because of the new T2 chip and SecureBoot, as well as a lack of drivers for the new NVME drive and keyboard/trackpad, nothing works. See here for more info https://github.com/Dunedan/mbp-2016-linux/issues/71..

I'll try booting from Windows and changing it from there later today.

**Comment by jonluca** [comment]
Alright, I used Bootcamp and followed [this guide](https://www.wikihow.com/Change-a-Computer%27s-Mac-Address-in-Windows), the regedit version. 

It successfully changed the mac address. This confirms that the change is not hardware - it's either a change in the kernel or a change in the `ifconfig` binary. 

![img_1855](https://user-images.githubusercontent.com/13029040/50308763-8e47f300-049c-11e9-8225-a8e13922fb2d.jpg)

Can anyone with an older version of macOS upload their `ifconfig` binary? The one on my 2018 MBP on Mojave has MD5 (/sbin/ifconfig) = 0c60b4d4632aa1db59b69584e2a3b09b

**Comment by jonluca** [comment]
It might be a change to the driver in the newest WiFi cards. AFAIK the driver needs to implement the `setProperties` in IOKit. Apple might've disabled this, either intentionally or accidentally, in the newest chipset drivers. 

Some possible helpful information for anyone reading this thread later:

* A `dapptrace` when attempting to change mac addresses - https://gist.github.com/jonluca/0c8477e2a6194b5adb23fc45e71b8c1a. This was run with `sudo dapptrace -ac ifconfig en0 ether ce:a1:fc:be:ac:a1 > functrace.txt 2>&1`

* All syscalls made by `ifconfig` when changing mac addresses - https://gist.github.com/jonluca/4bf3348e94f43ff582b45c0f611b88cb

* IOReg output for `ARPT` https://gist.github.com/jonluca/389b572cc11d0f6ece4dfbfdb3982a4f

* System report for Wifi Card https://gist.github.com/jonluca/262a63019b8419168900c6ed79c98521

Does anyone have experience with macos drivers or changing hardware properties from userland? 

Also the other weird thing is that in this thread we have 2 people reporting this issue on A) Older macbooks and B) on older versions of macos (i.e. not Mojave). Can we figure out if that's true or if their issue is something else (I'd guess permissions related). 

@frxst can you post your chipset information? System Report -> Network -> WiFi information should be enough.

**Comment by blaesus** [comment]
@jonluca
My data points: 

```
MBP2018 + High Sierra = failure  // As I originally reported
MBP2018 + Mojave = failure  // My current setup
MBP2017 + High Sierra = OK
```

**Comment by lucafrost** [comment]
@jonluca 
Here's my chipset info: https://gist.github.com/frxst/05b50c0e4f063154f1c999af83a6716d

**Comment by ghost** [comment]
MBP 2018 13 inch here. Changed MAC address on Bootcamp Windows 10 with tmac without any problem. The issue should be software related.

**Comment by timcampos** [comment]
Note: I have a 2015 Macbook Air running Mojave 10.14.2 - with this device I am able to change my MAC address no problem.

My 2018 Macbook Pro running Mojave 10.14.2 - no such luck. 

Has anyone tried disabling SIP and does that help?

**Comment by wildone** [comment]
changing last chars worked for me

**Comment by ghost** [comment]
> changing last chars worked for me

Could you expand on that? Do you have a MBP 2018?

**Comment by danipolo** [comment]
> changing last chars worked for me

please expand this, thanks

**Comment by killparty** [comment]
> changing last chars worked for me

Doesn't work for me

**Comment by joshm91** [comment]
I'm on a mid-2015 15inch mbp on 10.13.6 and can confirm that `sudo ifconfig en0 ether aa:bb:cc:dd:ee:ff` no longer successfully changes the mac address for me either.

**Comment by infracritical** [comment]
I have a MBP 15 as well, and that too, does not work.  I am running Mojave 10.14.2.

**Comment by joachimtingvold** [comment]
Did anyone try using older ifconfig binaries? (from MacOS releases known to work). Would be interesting to see if it would work, and if it does, if it works on both 2018 and pre-2018 MBPs.

**Comment by jonluca** [comment]
@jallakim 

The issue is not the macOS version - it's the new MBPs. I thought there might be a difference in binaries but unfortunately they are the same. 

I just tried changing the mac address on a 2016 MBP on 10.14.2 (18C54) and it works.
 
<img width="587" alt="screen shot 2019-01-21 at 3 13 54 pm" src="https://user-images.githubusercontent.com/13029040/51503354-6dbad380-1d8f-11e9-9b06-9491cb3e3b20.png"> 

The hash matches that of the 2018 MBP, which means that it's a driver difference. Now we need to find out if it's an intentional change or accidental regression by Apple.

**Comment by joachimtingvold** [comment]
@joshm91 stated a few comments above that it did *not* work on his mid-2015 MBP.

**Comment by jonluca** [comment]
@joshm91 can you post your System Information Hardware and Wifi pages and the output of the same commands I ran above?

```
sudo ifconfig en0
sudo ifconfig en0 ether 78:4f:43:95:47:2e
sudo ifconfig en0
```

If I had to guess he has a different issue.  They are on 1) a confirmed working version of the hardware and on 2) 10.13, which is the older version of macos, which also worked.

**Comment by slangava** [comment]
Updated to 10.14.3 on a MBP 13 2018 and still doesn't work

**Comment by jdraths** [comment]
I have an early 2015 MBP, recently updated to OS 10.14.1
I have the same problem as described above... cannot change my mac address.

chipset info [here](https://gist.github.com/jdraths/5144e2d88a7266e54a469cc26f9d8970)

**Comment by jdraths** [comment]
chipset info [here](https://gist.github.com/jdraths/5144e2d88a7266e54a469cc26f9d8970)

**Comment by MiroFurtado** [comment]
Also have this issue! 2017 MBP got this issue after updating to Mojave

**Comment by joachimtingvold** [comment]
I have an on-going case towards Apple Support regarding this matter. Will post info if/when I hear something. If I don't get any definitive answer, or if it takes forever to get an answer, I'll provide you with a case number, so that you can create cases for yourself, referring to the same case, possibly giving the issue more attention.

**Comment by alextidydx** [comment]
I bought one 13" mid 2018 till it died, it was replaced. I can tell you that on the exactly same os they behave sometimes differently, case was with touch id. Finder was crashing even on an empty machine. Couldn't and still can't change MAC, it's just ridiculous. It couldn't remember my apple id.

Nice work Apple, :applause:, way to go to communism!

**Comment by bruhadze** [comment]
I also have same issue. Running Mojave 10.4.4 on 2018 MacBook Pro 15”

**Comment by StewGoin** [comment]
10.14.2 on 2018 MBP 15" -- also can't change the MAC.

Same OS on a mac mini late 2012 -- worked fine.

**Comment by roes888** [comment]
MBP 2017 OS Version 10.14.2 (18C54)
`roes@MacBook-Pro ~/> spoof-mac list --wifi`
`- "Wi-Fi" on device "en0" with MAC address (ORIGINAL) currently set to (CHANGED)`

It's working for me. I give star this repo. Thanks!

**Comment by davkap92** [comment]
Seems to be working for me on 10.14 older mbp 2012 though, it didn't change in wifi advanced -> hardware but I see the change in ifconfig. thanks :)

**Comment by RamboRogers** [comment]
Doesn't work on MB Air 2018.

**Comment by adib** [comment]
I've posted Bug Report `48549933` to Apple on this.

**Comment by jgtoriginal** [comment]
Following @jonluca I installed a Linux VM.
It turns out that changing the MAC Address is OK there.
Then I went back to couple of old mac -both on Mojave, but from previous years- and checked that they all have the same version of ifconfig.
At this point, I'd assume there's something different on the driver that receives ifconfig's instructions.
But since that goes completely under the hood on OSX, I don't think there's an easy way of amending it.

**Comment by joachimtingvold** [comment]
> Following @jonluca I installed a Linux VM.
> It turns out that changing the MAC Address is OK there.

Does the change also reflect in Mac OS? (i.e. change the MAC via the Linux VM, and then check if Mac OS registers/uses that new MAC?).

**Comment by jgtoriginal** [comment]
No, it doesn't @jallakim probably because the linux OS is wrapped on the VM container.
Maybe with a bootable Linux USB, one might be able to override that permanently.

**Comment by joachimtingvold** [comment]
I'm guessing you're just changing the MAC for the virtual interface within the VM then, not really doing anything at all with the actual "physical" network card. Not really relevant, to be honest. You'd have to actually boot the machine into Linux if the test is to be relevant.

**Comment by jgtoriginal** [comment]
That's what I meant by,
`Maybe with a bootable Linux USB, one might be able to override that permanently.` @jallakim 
Which I will probably do, but I'm not sure I'm going to update you with such an encouraging comment.
`Not really relevant, to be honest` =)
Tbh, you should mind your manners. But I'll keep you posted anyway.
Have a good one!

**Comment by ookangzheng** [comment]
> Note: I have a 2015 Macbook Air running Mojave 10.14.2 - with this device I am able to change my MAC address no problem.
> 
> My 2018 Macbook Pro running Mojave 10.14.2 - no such luck.
> 
> Has anyone tried disabling SIP and does that help?

Tried disable SIP Mbpr 2018 15inch latest version... not working

**Comment by RamboRogers** [comment]
Doesn't seem to work for me.

Thanks,

Matthew Rogers

**Comment by jgtoriginal** [comment]
I just tried booting on Linux with a live usb stick.
It was basically impossible, I can get pass all security settings, but once loading the USB stick it get's blocked with err -14.
It turns out that new macs have a new T2 security chip, which basically disallows you from booting on Linux. You can find more details on the following links further down.
So I assume from now onwards bypassing this barriers would be just like jailbraking iOS.
In this case we'd need to gain full access first, then load linux, finally change the mac address.

* [Booting Linux Is Impossible On New Apple Hardware](https://www.forbes.com/sites/jasonevangelho/2018/11/06/booting-linux-is-impossible-on-new-apple-hardware/#5391f3727e1e)
* [Macs to Linux fans: Stop right there, Penguinista scum, that's not macOS. Go on, git outta here](https://www.theregister.co.uk/2018/11/06/apple_mac_linux_woes/)

**Comment by jonluca** [comment]
@jgtoriginal You can still boot linux if you disable some of the secure boot settings, following this guide by Apple [here](https://support.apple.com/en-us/HT208330). 

However, some of the drivers for the new MBP are missing/not fixed yet so it won't work. You can follow that discussion on [this alternate issue.](https://github.com/Dunedan/mbp-2016-linux/issues/71). I was able to get Arch halfway working in single user mode - only issue is the keyboard doesn't work. 

I also highly doubt that booting linux live usb you'd be able to override it permanently. The issue is that the mac address is permanently flashed to the WiFi card. AFAIK you can't overwrite that on MBPs. Any time you spoof your mac address on Linux/macOS/Windows you're just changing the kernel/in memory value, not the actual hardware data.

When it gets read into the OS during the initialization of the network stack it's then part of memory, and can just be freely changed (or at least you used to be able to).

I *think* we've isolated the issue to the driver or kernel. Since Bootcamp windows is able to change it, it's not a hardware issue. 

Anyone know someone particularly proficient with the Apple networking stack or their hardware drivers? I've tried tracing the syscalls but they always end up at `ioctl` and I'm stuck.

**Comment by jgtoriginal** [comment]
@jonluca Thanks for your update, you are right: you can `barely` boot linux, I just got to your very same case scenario following those very same steps by then.

I just don't think this is a driver or kernel `issue`, it looks to me like very inline with apple ways of profiling, where the MAC address is a key value. 

Anyway, thanks for your update!

**Comment by joshhunte** [comment]
Still the same in MacOS Mojave 10.14.5 update on a 15" MacBook Pro 2018. 

Has anyone had success running MacOS but using an external WiFi adapter?

**Comment by ookangzheng** [comment]
> Still the same in MacOS Mojave 10.14.5 update on a 15" MacBook Pro 2018.
> 
> Has anyone had success running MacOS but using an external WiFi adapter?

Im using https://www.gl-inet.com/products/gl-usb150/ USB Router to spoof my MAC address 
I plugged it into my powerbank as power source. Then do wifi-Repeater mode to my school / office /coffee shop public wifi

**Comment by danielehrhardt** [comment]
Same Issue with MacOS 10.15 :(

**Comment by joshhunte** [comment]
> > Still the same in MacOS Mojave 10.14.5 update on a 15" MacBook Pro 2018.
> > Has anyone had success running MacOS but using an external WiFi adapter?
> 
> Im using https://www.gl-inet.com/products/gl-usb150/ USB Router to spoof my MAC address
> I plugged it into my powerbank as power source. Then do wifi-Repeater mode to my school / office /coffee shop public wifi

I need to be able to spoof WiFI Network Adapter Address and for it to appear in MacOS.
Will that USB Router work?
Thanks

**Comment by Swang007** [comment]
Ditto, 10.14 & 10.15 Beta (19A487m). It's a shame Apple hasn't brought this to light.

**Comment by joshhunte** [comment]
"MacBook **Pro**" 
Apparently this does not even work for external USB NICs. 
Soon you will have to Jailbreak MacOS.
Thanks Apple!

**Comment by caglorithm** [comment]
Macbook Pro 2019 13 inch, same issue. My guess is Apple seems to have removed the functionality on purpose (which is outragous).

**Comment by lbarthon** [comment]
MBP 2018 15 inch, the issue is still here.
What's Apple's response on the bug report 48549933 ?

**Comment by joshhunte** [comment]
> MBP 2018 15 inch, the issue is still here.
> What's Apple's response on the bug report 48549933 ?

From what I can gather, so far it appears Apple is not considering this as a bug rather a security feature.

**Comment by jgtoriginal** [comment]
> > MBP 2018 15 inch, the issue is still here.
> > What's Apple's response on the bug report 48549933 ?
> 
> From what I can gather, so far it appears Apple is not considering this as a bug rather a security feature.

Is that how they call profiling now? =D
Anyway, do you have any quote you can point us to for that @joshhunte ?

**Comment by joshhunte** [comment]
> > > MBP 2018 15 inch, the issue is still here.
> > > What's Apple's response on the bug report 48549933 ?
> > 
> > 
> > From what I can gather, so far it appears Apple is not considering this as a bug rather a security feature.
> 
> Is that how they call profiling now? =D
> Anyway, do you have any quote you can point us to for that @joshhunte ?

Sure. Although an unconfirmed source, it sounds 100% plausible... This is Apple we are talking about...

https://forums.developer.apple.com/thread/106768

_Alright everyone.
My ticket has been closed and I pinged a bunch of friends I have that work at Apple HQ.
Final result. This is not a bug. Apple is removing this feature for security reasons. This makes no sense since doing this does not put the individual doing it at a security risk. But I don't. Im so done with the platform. You can't just remove ifconfig functionality. Thats not how any of this works.__

**Comment by total3dx** [comment]
What da hell hell?l!!

**Comment by feross** [comment]
This is the relevant post:

<img width="837" alt="Screen Shot 2019-07-10 at 4 03 00 PM" src="https://user-images.githubusercontent.com/121766/61010700-3a173a00-a32c-11e9-863e-4e0b5a887a8b.png">

**Comment by RamboRogers** [comment]
Privacy, FILE NOT FOUND.

Thanks,

Matthew Rogers

**Comment by halo** [comment]
To be fair, since iOS 8, MAC addresses are still randomly changing every 15 minutes on mobile devices. 

That's clearly a privacy feature and Apple would not put [this much effort](https://www.wired.com/story/apple-find-my-cryptography-bluetooth/) into privacy protection, to then entirely throw it over board only on macOS. I would grant Apple the benefit of doubt until more details surface.

> Apple is removing this feature for security reasons

I must admit, though, that I cannot come up with a reason related to security for disabling this on macOS entirely.

Just on a side note, if MAC address privacy were a top priority, iOS 10 would not have caused MAC randomization to be effectively useless [since 2016](https://www.researchgate.net/publication/314361145_A_Study_of_MAC_Address_Randomization_in_Mobile_Devices_and_When_it_Fails) (page 11):

> In June 2016, midway through our research, iOS 10 was released. Inexplicably the addition of an Apple vendor speciﬁc IE was added to all transmitted probe requests. This made identiﬁcation of iOS 10 Apple devices trivial regardless of the use of MAC address

That research has been confirmed [in 2019](https://arxiv.org/pdf/1904.10600.pdf) (page 9)

> Finally, the client device transmits an 802.11 authentication frame, in which the source address is the *global public* MAC address of the device. Strangely, we observe that probe request frames also use the *global public* MAC address of the device; this is unusual because iOS devices generally randomize MAC addresses in probe requests when in an un-associated state.

**Comment by alextidydx** [comment]
So now, if I need to change a MAC I need to have a dongle pack? do you sell 100 for $20? Don't you think it's ridiculous? This message 100% wasn't from a security guy at Apple. Just customer service. If they think they think it's ok (which I think is a violation of privacy) so bootcamp and linux then

**Comment by jgtoriginal** [comment]
Not possible either I'm afraid...

**Comment by PaulRBerg** [comment]
I confirm this issue on MBP Late 2016 with Mojave 10.14.6. I sent Apple my feedback on this using the template above.

It's particularly annoying because the city I'm stuck in for the next 2 weeks has many WiFi spots that limit users' download size and time allowance. As a digital nomad, it is an awful situation to be in.

**Comment by feross** [comment]
> So now, if I need to change a MAC I need to have a dongle pack?

Hah, this is actually a workaround that would probably work. There are [tiny USB wifi dongles](https://amzn.to/2ZuowNt):

[<img src="https://user-images.githubusercontent.com/121766/62418049-c4de1280-b614-11e9-80c3-d6f0cc65d4c5.jpg" width=120 />](https://amzn.to/2ZuowNt)

And you would need to combine that with a USB-A to USB-C dongle since you're presumably using a Mac with USB-C only if you've run into this issue. Here's [a tiny one](https://amzn.to/2KpZU1L):

[<img src="https://user-images.githubusercontent.com/121766/62418061-0e2e6200-b615-11e9-92ed-cc2714c79bb7.jpg" width=240 />](https://amzn.to/2KpZU1L)

You'd want to ensure that the dongle you buy has a MAC address that can be modified. Or, for maximum hilarity, you can buy 5-10 wifi dongles and swap them out whenever your WiFi time limit is up.

Welcome to Apple Life™️

![2ix8htA](https://user-images.githubusercontent.com/121766/62418082-a298c480-b615-11e9-8641-bc8cb54b4e8f.jpg)

**Comment by deuscielo** [comment]
Yes I can confirm this usb WiFi dongle works on a 2018 MacBook Pro

**Comment by nelsonjchen** [comment]
@deuscielo can you confirm if you can change the MAC address on it?

**Comment by cromatikap** [comment]
:laughing:

**Comment by cromatikap** [comment]
I just tried `sudo ifconfig en0 ether aa:bb:cc:dd:ee:ff` on a friend's macOS and it seemed to work (ifconfig show the new mac address) on 10.14 macOS version

**Comment by joshhunte** [comment]
> I just tried `sudo ifconfig en0 ether aa:bb:cc:dd:ee:ff` on a friend's macOS and it seemed to work (ifconfig show the new mac address) on 10.14 macOS version

Is that on a MBP 2018 on newer? The issue only occurs on newer MBPs.
Can anyone confirm that you can change the MAC address of an external dongle?

**Comment by dsedivec** [comment]
FYI I tried a TP-Link Archer T3U USB NIC on a 2019 MacBook Pro running macOS 10.14.6, and I was **not** able to change the MAC address via `sudo ifconfig en9 ether 50:3e:aa:66:66:66`.  (`50:3e:aa` are the first three octets of the device's original MAC.)

The command produced no output, the MAC address did not change according to a subsequent `ifconfig en9` command.

(And also I've now had to install some slightly scary TP-Link utility and kernel drivers to make it work, all of which seem to be 32-bit.  Will now rush to uninstall this software ASAP.)

**Comment by feross** [comment]
@dsedivec Thanks for looking into this. What a bummer.

**Comment by MediumDragon** [comment]
http://www.tensionsoftware.com/osx/macmacspoof/

"Optimized for macOS 10.14 (Mojave)."

"Native Intel 64 bit to take full advantage of the power of the latest Macs"
 
Am I missing something or did this guy seem to figure it out?

**Comment by feross** [comment]
@MediumDragon It's likely that he hasn't tested it on a 2018 or newer MBP. It probably works great with Mojave on older Macbooks. But perhaps someone can buy it and see if it works?

**Comment by MediumDragon** [comment]
Like MBP 2015? I got a 2015 and a 2018 sitting next to each other. I think its free to try. ill check it out.

**Comment by MediumDragon** [comment]
well, requires a license even tho website says free to try.

**Comment by dsedivec** [comment]
@MediumDragon From [the Mac MACSpoof user manual](http://sec.ecleti.com/osx/macmacspoof/Mac%20MACSpoof%20User%20Guide.pdf):

> On some Mac it may not Work
>
> Yes some Mac (in detail new MacBook Pro from 2018 and maybe successive, nothing is for sure here because Apple has no official info about that) may refuse to change MAC value because Apple did it by purpose, locking the possibility to change MAC value to the ports.  If you are using one of these Mac and you need to spoof the MAC ports you need to change hardware.  It seems there is no way to spoof the MAC values for these machines. No way.

**Comment by dsedivec** [comment]
FYI I just tried the same TP-Link Archer T3U USB 802.11ac NIC passed through to Ubuntu 18.04 running in a Parallels VM under macOS, and I was able to increment the low order byte of the NIC's MAC (`ip link set ... addr ...`), associate to a network, and send pings to another host so that I confirmed I saw the changed MAC on the wire (via tcpdump).  I did this in case there was any question that the mechanism preventing MAC address changing was somehow in a lower layer than macOS.

(The NIC was behaving very oddly, but that may have been due to the combination of kernel/rtl8822bu driver I was using, and/or the fact that I was running Linux in a VM.)

**Comment by harshanand120** [comment]
ok. so i have a MacBook Pro 2018 base model. i am on developer beta 5 of MacOS Catalina (build 19a526h) and i tried changing mac address of en0 (wifi) with sudo ifconfig en0 ether <mac-address> and it works. it never worked before but now its working flawlessly.

**Comment by jonluca** [comment]
~It's working for me as well.~

<img width="538" alt="Screen Shot 2019-08-17 at 8 07 50 AM" src="https://user-images.githubusercontent.com/13029040/63213864-277be780-c0c6-11e9-8b84-4ac8d4e1be74.png">

~Success~ 

edit: *might* not be working. need to research a little more. if someone else can confirm as well that would be helpful 😄

**Comment by harshanand120** [comment]
Can you please specify ur mac model and which issue are you facing. Just want to know bcz for me its been working as expected but I couldn’t find any information online about this anywhere.

**Comment by jgtoriginal** [comment]
@jonluca It's working for me. At least if I change the mac address and do an `nmap` of the network from another device, I can see the change reflected at a network level.

**Comment by tmthecoder** [comment]
I tried on Mojave 10.14.6 and it still doesn't work for me

**Comment by feross** [comment]
Can someone else who's running Catalina report whether or not this issue has been resolved?

**Comment by nz4ypt** [comment]
It works for me in beta 5 and now beta 6 

I’m on 13” mbp 2018 with Touch Bar.

**Comment by Berlin91** [comment]
this issue has closed?

**Comment by blaesus** [comment]
@Berlin91 No, it has not. However, previous reports suggest that spoofing would work again under macOS 10.15 – see comments above.

**Comment by gcpmusic** [comment]
On my 15” mbp 2017 with Touch Bar with Mojave 10.14.5 and I can spoof all MacAddress with no problem. On the some machine but booting from Catalina beta 6 I could spoof only the wi-fi, with beta 7 problem was solved but with the recent beta 8 some issue of beta 6 :-(

So looks like is not hardware issue here but if the OS block it. Let's hope that the final Catalina release would work.

**Comment by Mfgrolf** [comment]
10.14.6 on a 2016 15" MBPro: ifconfig works like a charm
10.14.6 on a 2019 13" MBPro: ifconfig shows me a middle finger when I try to change MAC-Adresses.

Thanks, Apple. I hope they get this fixed latest in Catalina or this is the last Mac I will own.

**Comment by diwu1989** [comment]
Catalina 10.15 gold master just released.

Can someone confirm whether it works with SpoofMac with 2018 15" MBPro?
Just wanted confirmation before I go through the troubles of doing OS upgrade.

**Comment by harshanand120** [comment]
I have a 2018 13 inch MacBook Pro and yes it works on Catalina GM Release.
It should be working on 15 inch as well

**Comment by jamescoletti** [comment]
Also confirming it works on Catalina 10.15 public release (build 19A582a) which is a different build than the GM (19A583). In System Preferences > Network > Wi-Fi (Advanced), it still shows the default hardware address, but the actual broadcasted address does change after doing a `sudo ifconfig en0 ether ...`

**Comment by gcpmusic** [comment]
I just update last beta with the recent final release of catalina and for a while my mac address spoof script worked fine on all interfaces possible. Now it start again blocking the ethernet spoof however the wi-fi and bridge spoofs just fine. I guess has to do with the realtek ethernet usb adapter which doesnt update the drive to the new drive framework. Any suggestion? I do have SIP disabled!
Thanks in advance.

**Comment by joshhunte** [comment]
Catalina Public release - En0 Wireless Spoof Working for me on MBP 2018.

I’m glad they fixed this or reversed their “Security” decision.

**Comment by jonluca** [comment]
Can confirm that it now works across all devices on Catalina. Wow, feels good after a 15 month long GitHub issue. 

@feross I think this issue can be closed. Might want to add a notice in app when you're running it on Mojave.

**Comment by blaesus** [comment]
Agree to close the issue. At long last, spoofing works again with Catalina for Macbook Pro 2018. Even the automatic reset on start-up works.

## For new comers to this issue:  basically, please upgrade to Catalina

**Comment by gcpmusic** [comment]
No shouldnt be closed as with wired ethernet adapter doesnt work. Please specify on which interface you are commenting. On Wi-Fi always worked on all release. Thank you.

**Comment by fborges** [comment]
Running MacOS 10.15 on a 15" MBP 2019, not working for me :/

**Comment by adudek16** [comment]
I was not able to change my MAC with my belkin usb-c ethernet adapter but worked on my hub.

**Comment by feross** [comment]
I can confirm that changing the Wi-Fi interface MAC address works on a MacBook 13" 2018 with Catalina 10.15.1 (19B88).

**Comment by Muhamed-Hamid** [comment]
Not working on catalina 10.15.1, was working before the upgrade

**Comment by jgtoriginal** [comment]
@Muhamed-Hamid it does work on Catalina 10.15.2 

<img width="743" alt="working_on_catalina_10 15 2" src="https://user-images.githubusercontent.com/1785392/69726750-ee5d0580-10ff-11ea-9423-47558e60903a.png">

**Comment by Muhamed-Hamid** [comment]
@jgtoriginal  This is only on spoof list, if you checked your advanced wifi settings from network you will find the shown mac address, this spoof doesn't change a thing if you really want to be hidden. If something little advanced firewall will detect the real mac address. 

I think It needs to be set with ifconfig so it would change the real hardware address.

**Comment by gcpmusic** [comment]
ifconfig only read or set a fake address. The real hardware address can't be changed and can be read with networksetup -listallhardwareports. If you really want to be hidden, all macaddress must be blocked in the router and to connect, you must use a fake macaddress !!

**Comment by Muhamed-Hamid** [comment]
ifconfig was able to change the appearing mac address in network settings which reflects over any communications, but now it's not. just masking it out and not reflect over any firewall inspection

**Comment by gcpmusic** [comment]
Not here on my MacBook, ifconfig still works fine and mask correctly all my macaddress!

**Comment by jgtoriginal** [comment]
@Muhamed-Hamid It does work, just go to your router or do an `nmap` on any other device connected to the same network and you will see that the mac address for your computer does change. When you spoof you don't change your physical address, you rather mask it and show a different one.

**Comment by gcpmusic** [comment]
That's correct.

**Comment by alextidydx** [comment]
> @Muhamed-Hamid It does work, just go to your router or do an `nmap` on any other device connected to the same network and you will see that the mac address for your computer does change. When you spoof you don't change your physical address, you rather mask it and show a different one.

I'm a bit confused, ok, physical MAC won't change. Then what's the point to change MAC in ifconfig at all? Does it mean that whatever I change MAC or not, all routers around still will use my hardware MAC for communications?

**Comment by gcpmusic** [comment]
No all the call just see ifconfig response. However as I did mention many time early you have to block the real address in your router otherwise it will pass true at boot before you change it !!!
Basically at boot you shouldnt connect at all to the net as your macaddress is blocked in the router and only when you change it you will be able to connect !! both ethernet and wi-fi.

Note: you see your real address just because you own the machine where the macaddress is written on the hardware, that's the reason why cant be changed but everyone outside your computer can only read it by ifconfig or other methods but will only see the fake one!!!

In fact after you spoof it correctly, check your router and you will see the fake one. If not  . . you did something wrong!

**Comment by joshhunte** [comment]
Hello, as you all know this issue was fixed on MBP 2018 with macOS Catalina. However I have now upgraded to MacBook 16 inch and and although I see the value reflected in terminal, it is not being reflected in the software. Note - I see the Mac change reflected on previous MacBook.

**Comment by dionhouston** [comment]
Apologize in advance if this doesn't apply to this case, but I found this thread when googling my problem.  I found on my 2019 mbp that "ifconfig en0 ether ..." didn't work as expected for changing the mac address.  Looking into it a bit further, it seems to be a problem with the change of the default shell from bash to zsh.  When I went to bash ("sudo /bin/bash") and did the same command it changed the mac as expected...

**Comment by harshanand120** [comment]
I guess that is because u ran the command without sudo. But when u changed the shell using “sudo bin/bash” all commands after that run as sudo. 
Try doing “sudo ifconfig en0 <mac>”.
I have tried doing so on a 16 inch mbp and can confirm it works.

**Comment by yusufk** [comment]
What's the latest on this? 

Doesn't seem to work on 10.15.2..

**Comment by onpaws** [comment]
I found I had to change `ifconfig en0 ether ...` to `ifconfig en0 lladdr ...` to get it working.
Also I had to have the WiFi interface on, which seems wrong but was necessary apparently.

macOS 10.15.3
MBP 16"

**Comment by allyoucaneattogo** [comment]
again we should open again this issue on Catalina 10.15.4 it doesn't work again

**Comment by harshanand120** [comment]
I am on MacBook Pro 2018 13 inch. Mac address spoofing still works using "sudo ifconfig en0 ether _mac_" or "sudo ifconfig en0 lladdr _mac_" on my machine as well as MacBook Pro 16 inch.

**Comment by onpaws** [comment]
> again we should open again this issue on Catalina 10.15.4 it doesn't work again

Without more specific info and repro steps, "it doesn't work again" is not a productive or helpful comment to anyone on this thread except you.

Next time can you please make the effort to provide a meaningful bug report with specifics? Consider reviewing guides online, for example
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

**Comment by allyoucaneattogo** [comment]
@onpaws Im sorry ill try @harshanand120 solution and if it won't work ill give an bug report

**Comment by onpaws** [comment]
> @onpaws Im sorry ill try @harshanand120 solution and if it won't work ill give an bug report

Good luck! :)

**Comment by robbhaker** [comment]
> ## Solution: Update to macOS 10.15 Catalina
> Updating to macOS 10.15 Catalina appears to fix the issue.
> 
> ## Original report
> I cannot randomize any MAC address with `spoof-mac`. The program returns fine, but the MAC addresses are not changed. I tried changing `en0` and `en1` and neither took effect. The Node.js `spoof` doesn't work either.
> 
> I tried rebooting or signing in as another user; neither worked.
> 
> By the way, `sudo ifconfig en0 ether aa:bb:cc:dd:ee:ff` doesn't work either.
> 
> spoof-mac version: **2.1.1**
> 
> <img alt="untitled" width="1541" src="https://user-images.githubusercontent.com/233354/42925131-a552ef0c-8b5f-11e8-91e9-6aa517d15e33.png">
> 
> <img alt="untitled 2" width="698" src="https://user-images.githubusercontent.com/233354/42925146-bc9cdb32-8b5f-11e8-9df1-e0be3c1afcce.png">
> 
> This is a new machine. I have another Macbook which runs on 10.12, where `spoof-mac` works just fine.
> 
> Thanks for making the tool! It is really helpful.

this is a eye opener.

**Comment by Danny-Z** [comment]
兄弟们， 我发现这样是可以的 
sudo ifconfig en3 ether 9A-44-B4-04-4E-49,
酱紫是不行的 9A:44:B4:04:4E:49

**Comment by jorpilo** [comment]
I manage to make it work on my Macbook M1...
1- disconnect from the wifi (don't turn the adapter off)
2- generate a mac address like `mac_address="$(networksetup -listallhardwareports | awk -v RS= '/en0/{print $NF}' | head -c 8):$(openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//')"`
3- `sudo ifconfig en0 ether "$mac_address"`
4- `networksetup -detectnewhardware`
5- Check the spoofed mac with `ifconfig en0 | grep ether | awk '{print $2}'` and `networksetup -listallhardwareports | awk -v RS= '/en0/{print $NF}'`
